const PROVINCES=["Aceh","Sumatera Utara","Sumatera Barat","Riau","Jambi","Sumatera Selatan","Bengkulu","Lampung","Kepulauan Bangka Belitung","Kepulauan Riau","DKI Jakarta","Jawa Barat","Jawa Tengah","DI Yogyakarta","Jawa Timur","Banten","Bali","Nusa Tenggara Barat","Nusa Tenggara Timur","Kalimantan Barat","Kalimantan Tengah","Kalimantan Selatan","Kalimantan Timur","Kalimantan Utara","Sulawesi Utara","Sulawesi Tengah","Sulawesi Selatan","Sulawesi Tenggara","Gorontalo","Sulawesi Barat","Maluku","Maluku Utara","Papua","Papua Barat","Papua Selatan","Papua Tengah","Papua Pegunungan","Papua Barat Daya"];
const CITIES={
"Aceh":["Banda Aceh","Aceh Besar","Aceh Utara","Aceh Timur"],"Sumatera Utara":["Medan","Deli Serdang","Binjai","Pematangsiantar"],"Sumatera Barat":["Padang","Bukittinggi","Padang Pariaman"],"Riau":["Pekanbaru","Dumai","Kampar"],"Jambi":["Jambi","Batanghari","Muaro Jambi"],"Sumatera Selatan":["Palembang","Banyuasin","Ogan Ilir"],"Bengkulu":["Bengkulu","Rejang Lebong"],"Lampung":["Bandar Lampung","Metro","Lampung Selatan"],"Kepulauan Bangka Belitung":["Pangkalpinang","Bangka","Belitung"],"Kepulauan Riau":["Batam","Tanjungpinang","Bintan"],"DKI Jakarta":["Jakarta Pusat","Jakarta Selatan","Jakarta Timur","Jakarta Barat","Jakarta Utara"],"Jawa Barat":["Bandung","Bekasi","Bogor","Depok","Cirebon","Tasikmalaya","Garut","Karawang"],"Jawa Tengah":["Semarang","Surakarta","Magelang","Tegal","Cilacap","Banyumas"],"DI Yogyakarta":["Yogyakarta","Sleman","Bantul","Kulon Progo"],"Jawa Timur":["Surabaya","Malang","Sidoarjo","Gresik","Kediri","Jember"],"Banten":["Tangerang","Tangerang Selatan","Serang","Cilegon","Lebak"],"Bali":["Denpasar","Badung","Gianyar","Buleleng"],"Nusa Tenggara Barat":["Mataram","Lombok Barat","Lombok Timur"],"Nusa Tenggara Timur":["Kupang","Ende","Maumere"],"Kalimantan Barat":["Pontianak","Singkawang","Kubu Raya"],"Kalimantan Tengah":["Palangka Raya","Kotawaringin Timur"],"Kalimantan Selatan":["Banjarmasin","Banjarbaru","Banjar"],"Kalimantan Timur":["Samarinda","Balikpapan","Kutai Kartanegara"],"Kalimantan Utara":["Tarakan","Nunukan","Bulungan"],"Sulawesi Utara":["Manado","Bitung","Tomohon"],"Sulawesi Tengah":["Palu","Donggala","Poso"],"Sulawesi Selatan":["Makassar","Gowa","Maros","Parepare"],"Sulawesi Tenggara":["Kendari","Baubau","Kolaka"],"Gorontalo":["Gorontalo","Bone Bolango"],"Sulawesi Barat":["Mamuju","Majene","Polewali Mandar"],"Maluku":["Ambon","Tual","Maluku Tengah"],"Maluku Utara":["Ternate","Tidore","Halmahera Barat"],"Papua":["Jayapura","Biak Numfor","Merauke"],"Papua Barat":["Manokwari","Fakfak","Kaimana"],"Papua Selatan":["Merauke","Asmat","Boven Digoel"],"Papua Tengah":["Nabire","Mimika","Paniai"],"Papua Pegunungan":["Jayawijaya","Yahukimo","Pegunungan Bintang"],"Papua Barat Daya":["Sorong","Raja Ampat","Sorong Selatan"]};
const BANKS=[
["BSU PERCAGALUH","Aceh","Aceh Besar","BSU","A"],["BSU Persada Yonif 117","Aceh","Aceh Besar","BSU","A"],["Bank Sampah Bina Bersama","Aceh","Aceh Besar","BSU","A"],["Bank Sampah Berseri","Sumatera Utara","Medan","BSU","A"],["BSI Medan Bersih","Sumatera Utara","Medan","BSI","A"],["Bank Sampah Andalan","Sumatera Barat","Padang","BSU","A"],["BSU Green Riau","Riau","Pekanbaru","BSU","A"],["Bank Sampah Jambi Lestari","Jambi","Jambi","BSU","A"],["Bank Sampah Musi Hijau","Sumatera Selatan","Palembang","BSI","A"],["Bank Sampah Bengkulu Sehat","Bengkulu","Bengkulu","BSU","A"],["Bank Sampah Lampung Berjaya","Lampung","Bandar Lampung","BSI","A"],["Bank Sampah Batam Bersih","Kepulauan Riau","Batam","BSU","A"],["Bank Sampah Jakarta Hijau","DKI Jakarta","Jakarta Selatan","BSI","A"],["Bank Sampah Ciliwung","DKI Jakarta","Jakarta Timur","BSU","A"],["Bank Sampah Bandung Juara","Jawa Barat","Bandung","BSI","A"],["Bank Sampah Bekasi Lestari","Jawa Barat","Bekasi","BSU","A"],["Bank Sampah Bogor Asri","Jawa Barat","Bogor","BSU","A"],["Bank Sampah Cirebon Resik","Jawa Barat","Cirebon","BSU","B"],["Bank Sampah Semarang Hebat","Jawa Tengah","Semarang","BSI","A"],["Bank Sampah Solo Berseri","Jawa Tengah","Surakarta","BSU","A"],["Bank Sampah Jogja Hijau","DI Yogyakarta","Yogyakarta","BSI","A"],["Bank Sampah Surabaya Green","Jawa Timur","Surabaya","BSI","A"],["Bank Sampah Malang Bersih","Jawa Timur","Malang","BSU","A"],["Bank Sampah Sidoarjo Asri","Jawa Timur","Sidoarjo","BSU","A"],["Bank Sampah Tangerang Lestari","Banten","Tangerang","BSI","A"],["Bank Sampah Serang Berkah","Banten","Serang","BSU","B"],["Bank Sampah Bali Resik","Bali","Denpasar","BSI","A"],["Bank Sampah Mataram Hijau","Nusa Tenggara Barat","Mataram","BSU","A"],["Bank Sampah Kupang Bersih","Nusa Tenggara Timur","Kupang","BSU","B"],["Bank Sampah Pontianak Lestari","Kalimantan Barat","Pontianak","BSU","A"],["Bank Sampah Borneo Hijau","Kalimantan Timur","Samarinda","BSI","A"],["Bank Sampah Banjarmasin Resik","Kalimantan Selatan","Banjarmasin","BSU","A"],["Bank Sampah Manado Eco","Sulawesi Utara","Manado","BSU","A"],["Bank Sampah Makassar Bersih","Sulawesi Selatan","Makassar","BSI","A"],["Bank Sampah Kendari Hijau","Sulawesi Tenggara","Kendari","BSU","B"],["Bank Sampah Ambon Lestari","Maluku","Ambon","BSU","A"],["Bank Sampah Ternate Bersih","Maluku Utara","Ternate","BSU","A"],["Bank Sampah Jayapura Hijau","Papua","Jayapura","BSU","B"],["Bank Sampah Sorong Lestari","Papua Barat Daya","Sorong","BSU","A"]
];
const RISKS=[["Jakarta", -6.2,106.82,92,"Tinggi"],["Bekasi",-6.24,107.0,88,"Tinggi"],["Bandung",-6.91,107.61,81,"Tinggi"],["Semarang",-6.97,110.42,76,"Tinggi"],["Surabaya",-7.25,112.75,84,"Tinggi"],["Medan",3.59,98.67,73,"Tinggi"],["Makassar",-5.14,119.42,70,"Tinggi"],["Denpasar",-8.65,115.22,62,"Sedang"],["Palembang",-2.99,104.76,68,"Sedang"],["Banjarmasin",-3.32,114.59,65,"Sedang"],["Pontianak",-0.02,109.34,61,"Sedang"],["Pekanbaru",0.51,101.45,58,"Sedang"],["Padang",-0.95,100.35,55,"Sedang"],["Manado",1.47,124.84,49,"Sedang"],["Jayapura",-2.53,140.72,42,"Rendah"],["Kupang",-10.17,123.61,44,"Rendah"],["Ambon",-3.7,128.18,46,"Rendah"]];
let map, markers=[], currentBankPage=1; const perPage=9;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function toast(msg){let t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2800)}
function populateSelects(){
  ["provinceFilter","bankProvince","reportProvince"].forEach(id=>{let el=$("#"+id);PROVINCES.forEach(p=>el.insertAdjacentHTML("beforeend",`<option>${p}</option>`))});
}
function setupCities(){
  $("#reportProvince").addEventListener("change",e=>{let c=$("#reportCity");c.innerHTML='<option value="">Pilih kota</option>'+(CITIES[e.target.value]||[]).map(x=>`<option>${x}</option>`).join("")});
}
function navigate(page){location.hash=page}
function renderPage(){
  let page=location.hash.slice(1)||"home";if(!$("#"+page))page="home";
  $$(".page").forEach(p=>p.classList.toggle("active",p.id===page));$$(".desktop-nav a").forEach(a=>a.classList.toggle("active",a.dataset.page===page));
  if(page==="map")setTimeout(initMap,50); if(page==="dashboard")setTimeout(initCharts,50); if(page==="menu")renderBanks();if(page==="reports")renderReports();
  window.scrollTo(0,0)
}
document.addEventListener("click",e=>{let el=e.target.closest("[data-page]");if(el){e.preventDefault();navigate(el.dataset.page)}})
function initMap(){
  if(map){map.invalidateSize();return}
  map=L.map("mapCanvas").setView([-2.5,118],4.7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);drawMap()
}
function riskColor(score){return score>=75?"#e66d55":score>=50?"#e3b74f":"#5cb982"}
function drawMap(){
  markers.forEach(m=>map.removeLayer(m));markers=[];
  let layer=$("#mapLayer").value; let province=$("#provinceFilter").value;
  RISKS.forEach(r=>{let [name,lat,lng,score,label]=r;if(layer==="risk"){let c=L.circle([lat,lng],{radius:Math.max(18000,score*480),color:riskColor(score),fillColor:riskColor(score),fillOpacity:.28,weight:1}).addTo(map).bindPopup(`<b>${name}</b><br>Indeks risiko: ${score}/100<br>Status: ${label}`);markers.push(c)}else{let c=L.circleMarker([lat,lng],{radius:9,color:"#fff",weight:2,fillColor:"#0b7651",fillOpacity:.9}).addTo(map).bindPopup(`<b>Bank sampah sekitar ${name}</b><br>Gunakan direktori untuk daftar fasilitas.`);markers.push(c)}});
  if(province){let sample=BANKS.find(b=>b[1]===province);if(sample){let r=RISKS.find(x=>x[0].toLowerCase().includes(sample[2].split(" ")[0].toLowerCase()))||RISKS.find(x=>x[0]===sample[2]);if(r)map.setView([r[1],r[2]],8)}}}
function renderPriority(){let data=[...RISKS].sort((a,b)=>b[3]-a[3]).slice(0,6);$("#priorityList").innerHTML=data.map(r=>`<div class="priority"><b>${r[0]}</b><span><span class="risk-label">${r[4]}</span> ${r[3]}/100</span></div>`).join("")}
function initCharts(){
  if(window._charts)return;window._charts=true;
  new Chart($("#compositionChart"),{type:"doughnut",data:{labels:["Organik","Plastik","Kertas","Lainnya"],datasets:[{data:[41,19,12,28]}]},options:{cutout:"72%",plugins:{legend:{position:"bottom",labels:{usePointStyle:true,font:{size:10}}}}}});
  new Chart($("#managementChart"),{type:"bar",data:{labels:["Terkelola","Tidak terkelola"],datasets:[{data:[31.8,68.2],borderRadius:8}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,ticks:{callback:v=>v+"%"}}}}});
  let top=RISKS.slice(0,7);new Chart($("#cityChart"),{type:"bar",data:{labels:top.map(x=>x[0]),datasets:[{label:"Indeks",data:top.map(x=>x[3]),borderRadius:7}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100}}}});
}
function bankFiltered(){let q=$("#bankSearch").value.toLowerCase(),p=$("#bankProvince").value,t=$("#bankType").value;return BANKS.filter(b=>(!q||b.join(" ").toLowerCase().includes(q))&&(!p||b[1]===p)&&(!t||b[3]===t))}
function renderBanks(){let data=bankFiltered(),pages=Math.max(1,Math.ceil(data.length/perPage));currentBankPage=Math.min(currentBankPage,pages);let start=(currentBankPage-1)*perPage;$("#bankCount").textContent=data.length;$("#pageInfo").textContent=`${currentBankPage} / ${pages}`;$("#bankGrid").innerHTML=data.slice(start,start+perPage).map((b,i)=>`<article class="bank-card"><div class="bank-top"><span class="bank-type">${b[3]}</span><span style="font-size:10px;color:#3d9767">● ${b[4]==="A"?"Aktif":"Perlu cek"}</span></div><h3>${b[0]}</h3><p>${b[2]}, ${b[1]}</p><div class="bank-meta"><span>♻ Fasilitas</span><span>Detail →</span></div></article>`).join("")||'<div class="panel" style="grid-column:1/-1">Tidak ada data yang cocok.</div>'}
function getReports(){return JSON.parse(localStorage.getItem("pb_reports")||"[]")}
function saveReports(x){localStorage.setItem("pb_reports",JSON.stringify(x))}
function renderReports(){let data=getReports();$("#reportBadge").textContent=data.length;$("#profileReports").textContent=data.length;$("#profilePoints").textContent=data.length*10;$("#reportList").innerHTML=data.length?data.slice().reverse().map(r=>`<div class="report-item"><div style="display:flex;justify-content:space-between;gap:8px"><b>${escapeHtml(r.title)}</b><span class="report-status">Menunggu verifikasi</span></div><p>${escapeHtml(r.description).slice(0,140)}${r.description.length>140?"…":""}</p><div class="meta"><span>${r.city}, ${r.province}</span><span>${new Date(r.date).toLocaleDateString("id-ID")}</span></div></div>`).join(""):'<p style="font-size:12px;color:#87958f;padding:20px 0">Belum ada laporan. Jadilah kontributor pertama.</p>';renderLeaderboard(data)}
function renderLeaderboard(data){let base=[["Eco Ranger","Jakarta",142],["Hijau Bersama","Bandung",118],["Sahabat Sungai","Surabaya",96],["Bumi Lestari","Medan",74],["Pengguna PlasticBank","Indonesia",data.length*10]];base.sort((a,b)=>b[2]-a[2]);$("#leaderboard").innerHTML=base.map((r,i)=>`<div class="rank"><span class="rank-num">#${i+1}</span><div class="rank-name">${r[0]}<small>${r[1]}</small></div><span class="rank-points">${r[2]} pts</span></div>`).join("")}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
$("#reportForm").addEventListener("submit",e=>{e.preventDefault();let fd=new FormData(e.target),reports=getReports();reports.push({title:fd.get("title"),province:fd.get("province"),city:fd.get("city"),category:fd.get("category"),description:fd.get("description"),lat:fd.get("lat"),lng:fd.get("lng"),date:new Date().toISOString()});saveReports(reports);e.target.reset();$("#reportCity").innerHTML='<option value="">Pilih provinsi dulu</option>';renderReports();toast("Laporan berhasil disimpan di perangkat ini.");})
["bankSearch","bankProvince","bankType"].forEach(id=>$("#"+id).addEventListener("input",()=>{currentBankPage=1;renderBanks()}));$("#resetBank").onclick=()=>{$("#bankSearch").value="";$("#bankProvince").value="";$("#bankType").value="";renderBanks()};$("#prevPage").onclick=()=>{currentBankPage--;renderBanks()};$("#nextPage").onclick=()=>{currentBankPage++;renderBanks()};$("#mapLayer").addEventListener("change",drawMap);$("#provinceFilter").addEventListener("change",drawMap);
$("#addBankBtn").onclick=()=>showModal(`<span class="eyebrow">KONTRIBUSI DATA</span><h2 style="font-family:Manrope">Tambah fasilitas</h2><p style="color:#71857b">Versi demo belum mengirim data ke server. Form ini dapat dihubungkan ke Supabase/Firebase pada tahap produksi.</p><button class="btn btn-primary full" onclick="closeModal()">Mengerti</button>`);
$("#editProfile").onclick=()=>{let n=prompt("Nama tampilan:",$("#profileName").textContent);if(n){$("#profileName").textContent=n;localStorage.setItem("pb_name",n);toast("Profil diperbarui.")}};
function showModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.add("show")}function closeModal(){$("#modal").classList.remove("show")}$("#modalClose").onclick=closeModal;$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
$("#mobileMenu").onclick=()=>{let n=$(".desktop-nav");n.style.display=n.style.display==="flex"?"none":"flex";n.style.position="absolute";n.style.top="74px";n.style.right="5vw";n.style.flexDirection="column";n.style.background="#fff";n.style.padding="10px";n.style.borderRadius="12px";n.style.boxShadow="0 15px 35px #0002"};
populateSelects();setupCities();renderPriority();$("#profileName").textContent=localStorage.getItem("pb_name")||"Pengguna PlasticBank";window.addEventListener("hashchange",renderPage);setTimeout(()=>{$("#splash").style.opacity="0";$("#splash").style.pointerEvents="none";setTimeout(()=>$("#splash").remove(),500);renderPage()},1300);
